version: 2
jobs:
  pr-check:
    working_directory: ~/webapp-frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install node_modules with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Install angularcli
          command: echo 'N' | sudo npm install -g @angular/cli@latest
      - run:
          name: Compiling code
          command: npm run build
      - run:
          name: Running unit test
          command: npm run test
  build:
    working_directory: ~/webapp-frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install node_modules with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Install angularcli
          command: echo 'N' | sudo npm install -g @angular/cli@latest
      - run:
          name: Install aws_cli
          command: sudo apt-get -y install awscli
      - run:
          name: Build code
          command: npm run build
      - run:
          name: Build deployment artifact
          command: zip -r ~/webapp_frontend.zip .
      - run:
          name: Copy artifact to S3
          command: aws s3 cp ~/webapp_frontend.zip s3://codedeploy.shalvikubal.me
      - run:
          name: Deploy code
          command: aws deploy create-deployment --application-name csye6225-webapp  --deployment-group-name csye6225-webapp-deployment --s3-location bucket=codedeploy.shalvikubal.me,bundleType=zip,key=webapp_frontend.zip
workflows:
  version: 2
  pr-check:
    jobs:
      - pr-check
  build-deploy:
    jobs:
      - build
      # - build:
      #     filters:
      #       branches:
      #         only:
      #           - master
